image: fedora:latest

before_script:
  - dnf install -y hugo tidy findutils
  - hugo version
  - tidy -version

pages:
  script:
  - hugo
  - find public/ -name "*.html" | while read page; do echo "Tidying $page"; tidy -config tidy_config.txt "$page" || true; done
  artifacts:
    paths:
    - public
  only:
    - current

variables:
  GIT_SUBMODULE_STRATEGY: recursive
