baseURL = "https://docs.openblox.org/"
languageCode = "en-us"
title = "OpenBlox API documentation"
disableKinds = ["RSS"]
disableHugoGeneratorInject = true
theme = "OpenBlox"
uglyURLs = true
pygmentsUseClasses = true

[Languages.en]
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[Languages.en.menu.main]]
name = "Wiki"
url = "https://wiki.openblox.org"
weight = 2
[[Languages.en.menu.main]]
name = "Repositories"
url = "https://git.openblox.org"
weight = 3
[[Languages.en.menu.main]]
name = "Mailing lists"
url = "https://lists.openblox.org"
weight = 4
[[Languages.en.menu.main]]
name = "Bugzilla"
url= "https://bugs.openblox.org"
weight = 5
[[Languages.en.menu.main]]
name = "Jenkins"
url = "https://ci.openblox.org"
weight = 6

[Languages.fr]
[[Languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1
[[Languages.fr.menu.main]]
name = "Wiki"
url = "https://wiki.openblox.org"
weight = 2
[[Languages.fr.menu.main]]
name = "Dépôts"
url = "https://git.openblox.org"
weight = 3
[[Languages.fr.menu.main]]
name = "Listes"
url = "https://lists.openblox.org"
weight = 4
[[Languages.fr.menu.main]]
name = "Bugzilla"
url= "https://bugs.openblox.org"
weight = 5
[[Languages.fr.menu.main]]
name = "Jenkins"
url = "https://ci.openblox.org"
weight = 6
